import os
from dotenv import load_dotenv
load_dotenv()
import psycopg2
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT

def create_postgres_schema():
    """Create PostgreSQL schema matching SQLite structure"""
    
    database_url = os.environ.get('DATABASE_URL')
    if not database_url:
        print("❌ DATABASE_URL environment variable not found!")
        return False
    
    print("="*80)
    print("POSTGRESQL SCHEMA CREATION")
    print("="*80)
    print(f"\n📊 Connecting to PostgreSQL...")
    
    try:
        conn = psycopg2.connect(database_url)
        conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
        cursor = conn.cursor()
        
        print("✅ Connected successfully!")
        print("\n🔨 Creating tables...\n")
        
        tables = [
            ("""
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                email TEXT NOT NULL UNIQUE,
                password_hash TEXT NOT NULL,
                role TEXT NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                is_protected INTEGER DEFAULT 0
            )
            """, "users"),
            
            ("""
            CREATE TABLE IF NOT EXISTS services (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """, "services"),
            
            ("""
            CREATE TABLE IF NOT EXISTS pipeline_stages (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                position INTEGER NOT NULL,
                color TEXT DEFAULT '#6c757d',
                is_default INTEGER DEFAULT 0,
                created_by_id INTEGER NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                description TEXT,
                is_protected INTEGER DEFAULT 0,
                FOREIGN KEY (created_by_id) REFERENCES users(id)
            )
            """, "pipeline_stages"),
            
            ("""
            CREATE TABLE IF NOT EXISTS user_profiles (
                user_id INTEGER PRIMARY KEY,
                avatar_path TEXT,
                bio TEXT,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
            )
            """, "user_profiles"),
            
            ("""
            CREATE TABLE IF NOT EXISTS leads (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                submitted_by_user_id INTEGER NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                full_name TEXT NOT NULL,
                email TEXT NOT NULL,
                phone TEXT NOT NULL,
                company TEXT NOT NULL,
                domain TEXT NOT NULL,
                services_csv TEXT NOT NULL,
                country TEXT NOT NULL,
                state TEXT NOT NULL,
                city TEXT NOT NULL,
                attachment_path TEXT,
                status TEXT NOT NULL DEFAULT 'Pending',
                current_manager_id INTEGER,
                accepted_at TIMESTAMP,
                rejected_at TIMESTAMP,
                assigned_at TIMESTAMP,
                assigned_bd_id INTEGER,
                current_stage_id INTEGER,
                deal_amount DECIMAL(10, 2),
                assigned_to_bd_at TIMESTAMP,
                industry VARCHAR(50),
                FOREIGN KEY (submitted_by_user_id) REFERENCES users(id),
                FOREIGN KEY (current_manager_id) REFERENCES users(id),
                FOREIGN KEY (assigned_bd_id) REFERENCES users(id),
                FOREIGN KEY (current_stage_id) REFERENCES pipeline_stages(id)
            )
            """, "leads"),
            
            ("""
            CREATE TABLE IF NOT EXISTS lead_activities (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                lead_id INTEGER NOT NULL,
                actor_id INTEGER NOT NULL,
                activity_type TEXT NOT NULL,
                title TEXT,
                description TEXT,
                due_at TIMESTAMP,
                completed_at TIMESTAMP,
                reminder_at TIMESTAMP,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE,
                FOREIGN KEY (actor_id) REFERENCES users(id)
            )
            """, "lead_activities"),
            
            ("""
            CREATE TABLE IF NOT EXISTS lead_social_profiles (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                lead_id INTEGER NOT NULL,
                platform TEXT NOT NULL,
                url TEXT NOT NULL,
                added_by_id INTEGER NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE,
                FOREIGN KEY (added_by_id) REFERENCES users(id)
            )
            """, "lead_social_profiles"),
            
            ("""
            CREATE TABLE IF NOT EXISTS lead_stage_history (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                lead_id INTEGER NOT NULL,
                from_stage_id INTEGER,
                to_stage_id INTEGER NOT NULL,
                changed_by_id INTEGER NOT NULL,
                note TEXT,
                changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE,
                FOREIGN KEY (from_stage_id) REFERENCES pipeline_stages(id),
                FOREIGN KEY (to_stage_id) REFERENCES pipeline_stages(id),
                FOREIGN KEY (changed_by_id) REFERENCES users(id)
            )
            """, "lead_stage_history"),
            
            ("""
            CREATE TABLE IF NOT EXISTS lead_assignments (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                lead_id INTEGER NOT NULL,
                manager_id INTEGER NOT NULL,
                assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                acted_at TIMESTAMP,
                deadline_at TIMESTAMP NOT NULL,
                status TEXT DEFAULT 'pending',
                is_initial_assignment INTEGER DEFAULT 1,
                FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE,
                FOREIGN KEY (manager_id) REFERENCES users(id)
            )
            """, "lead_assignments"),
            
            ("""
            CREATE TABLE IF NOT EXISTS lead_assignment_history (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                lead_id INTEGER NOT NULL,
                from_manager_id INTEGER,
                to_manager_id INTEGER NOT NULL,
                reassigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                reason TEXT NOT NULL,
                triggered_by TEXT NOT NULL,
                FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE,
                FOREIGN KEY (from_manager_id) REFERENCES users(id),
                FOREIGN KEY (to_manager_id) REFERENCES users(id)
            )
            """, "lead_assignment_history"),
            
            ("""
            CREATE TABLE IF NOT EXISTS bd_assignment_history (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                lead_id INTEGER NOT NULL,
                from_bd_id INTEGER,
                to_bd_id INTEGER NOT NULL,
                assigned_by_id INTEGER NOT NULL,
                reassigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                reason TEXT,
                FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE,
                FOREIGN KEY (from_bd_id) REFERENCES users(id),
                FOREIGN KEY (to_bd_id) REFERENCES users(id),
                FOREIGN KEY (assigned_by_id) REFERENCES users(id)
            )
            """, "bd_assignment_history"),
            
            ("""
            CREATE TABLE IF NOT EXISTS lead_edit_changes (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                lead_id INTEGER NOT NULL,
                editor_user_id INTEGER NOT NULL,
                field_name TEXT NOT NULL,
                old_value TEXT,
                new_value TEXT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE,
                FOREIGN KEY (editor_user_id) REFERENCES users(id)
            )
            """, "lead_edit_changes"),
            
            ("""
            CREATE TABLE IF NOT EXISTS lead_notes (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                lead_id INTEGER NOT NULL,
                author_user_id INTEGER NOT NULL,
                note_type TEXT NOT NULL,
                message TEXT NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE,
                FOREIGN KEY (author_user_id) REFERENCES users(id)
            )
            """, "lead_notes"),
            
            ("""
            CREATE TABLE IF NOT EXISTS notifications (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL,
                lead_id INTEGER NOT NULL,
                message TEXT NOT NULL,
                is_read INTEGER DEFAULT 0,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                notification_type TEXT DEFAULT 'info',
                sound_enabled INTEGER DEFAULT 1,
                FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
                FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE,
                CHECK (notification_type IN ('info', 'warning', 'success', 'assignment'))
            )
            """, "notifications"),
            
            ("""
            CREATE TABLE IF NOT EXISTS lead_targets (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                assigned_by_id INTEGER NOT NULL,
                assignee_id INTEGER NOT NULL,
                target_count INTEGER NOT NULL,
                period_start DATE NOT NULL,
                period_end DATE NOT NULL,
                target_type TEXT NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (assigned_by_id) REFERENCES users(id),
                FOREIGN KEY (assignee_id) REFERENCES users(id)
            )
            """, "lead_targets"),
            
            ("""
            CREATE TABLE IF NOT EXISTS assignment_settings (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                last_assigned_manager_id INTEGER,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                last_assigned_bd_id INTEGER,
                FOREIGN KEY (last_assigned_manager_id) REFERENCES users(id),
                FOREIGN KEY (last_assigned_bd_id) REFERENCES users(id)
            )
            """, "assignment_settings"),
            
            ("""
            CREATE TABLE IF NOT EXISTS migration_log (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                migration_name TEXT NOT NULL,
                run_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
            """, "migration_log"),
        ]
        
        for sql, table_name in tables:
            try:
                cursor.execute(sql)
                print(f"  ✅ Created table: {table_name}")
            except Exception as e:
                print(f"  ⚠️  Table {table_name}: {str(e)}")
        
        print("\n" + "="*80)
        print("✅ PostgreSQL schema created successfully!")
        print("="*80)
        
        cursor.close()
        conn.close()
        return True
        
    except Exception as e:
        print(f"\n❌ Error creating PostgreSQL schema: {e}")
        return False

if __name__ == '__main__':
    create_postgres_schema()
